### ISSUE TITLE
Windows not able to create credentials file

### ISSUE THREAD

**Issue by mjThrower12** [turnerlabs/samlkeygen#23]
Hello was this tool build to work on Window machines, I cant seem to get it to create the following file for my aws credentials C:\\Users\\mthrower/.aws\\credentials.tmp

when I run the samld command with the correct url domain and username, and the appropriate password for my username.

`Traceback (most recent call last):
  File "C:\Users\mthrower\AppData\Local\Programs\Python\Python37-32\Scripts\samld-script.py", line 11, in <module>
    load_entry_point('samlkeygen==1.3.1', 'console_scripts', 'samld')()
  File "c:\users\mthrower\appdata\local\programs\python\python37-32\lib\site-packages\samlkeygen\entry_points.py", line 199, in samld
    main()
  File "c:\users\mthrower\appdata\local\programs\python\python37-32\lib\site-packages\samlkeygen\entry_points.py", line 518, in main
    parser.dispatch()
  File "c:\users\mthrower\appdata\local\programs\python\python37-32\lib\site-packages\argh\helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "c:\users\mthrower\appdata\local\programs\python\python37-32\lib\site-packages\argh\dispatching.py", line 174, in dispatch
    for line in lines:
  File "c:\users\mthrower\appdata\local\programs\python\python37-32\lib\site-packages\argh\dispatching.py", line 277, in _execute_command
    for line in result:
  File "c:\users\mthrower\appdata\local\programs\python\python37-32\lib\site-packages\argh\dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "c:\users\mthrower\appdata\local\programs\python\python37-32\lib\site-packages\samlkeygen\entry_points.py", line 168, in authenticate
    merge_ini_files(files, TEMP_FILE)
  File "c:\users\mthrower\appdata\local\programs\python\python37-32\lib\site-packages\samlkeygen\entry_points.py", line 193, in merge_ini_files
    with open(target_file, 'wt') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mthrower/.aws\\credentials.tmp'`

**Comment by mtheadley** [comment]
I ran into the same problem.  If you create the '.aws' folder in your user directory (C:\users\mthrower), it will start working.
